general:
  report_frequency: 1
  enable_wandb_hook: 0
  verbose: 1

optimizer:
  type: adam
  parameters:
    learning_rate: 0.001
    beta1: 0.9
    beta2: 0.999
    weight_decay: 0
    eps: 1e-6
    amsgrad: 0

algorithm:
  type: sac
  parameters:
    batch_size: 256
    nstep: 1
    nstep_reward_reduction: sum
    num_critics: 1
    gamma: 0.995
    rho: 0.99

replay_buffer:
  type: uniform
  parameters:
    max_size: 4096
    min_size: 512

actor:
  type: parameter_noise
  parameters:
    a_low: -1.0
    a_high: 1.0
  
policy_model:
  type: SACMLP
  parameters:
    dropout: 0.0
    layer_sizes: [3, 128, 128, 1]

critic_model:
  type: MLP
  parameters:
    dropout: 0.0
    layer_sizes: [3, 128, 128, 1]

policy_lr_scheduler:
  type: cosine_annealing
  parameters:
    T_max: 5000

critic_lr_scheduler:
  type: cosine_annealing
  parameters:
    T_max: 5000
